// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_image_url`, `fetch_dangdang_cover`, `fetch_douban_cover`, `gb_extract_thumbnail`, `google_books_cover`, `ol_cover_by_isbn`, `ol_cover_by_title`, `ol_fetch_cover_id`

Future<String?> fetchCoverUrl({required String isbn, required String title}) =>
    RustLib.instance.api.crateApiBookCoverFetchCoverUrl(
      isbn: isbn,
      title: title,
    );
