// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BookDetail {
  final String isbn;
  final String price;
  final String pages;
  final List<BookLocation> locations;

  const BookDetail({
    required this.isbn,
    required this.price,
    required this.pages,
    required this.locations,
  });

  @override
  int get hashCode =>
      isbn.hashCode ^ price.hashCode ^ pages.hashCode ^ locations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookDetail &&
          runtimeType == other.runtimeType &&
          isbn == other.isbn &&
          price == other.price &&
          pages == other.pages &&
          locations == other.locations;
}

class BookInfo {
  final String title;
  final String author;
  final String publisher;
  final String callNo;
  final String docType;
  final String holdingsSummary;
  final String detailUrl;

  const BookInfo({
    required this.title,
    required this.author,
    required this.publisher,
    required this.callNo,
    required this.docType,
    required this.holdingsSummary,
    required this.detailUrl,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      author.hashCode ^
      publisher.hashCode ^
      callNo.hashCode ^
      docType.hashCode ^
      holdingsSummary.hashCode ^
      detailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          publisher == other.publisher &&
          callNo == other.callNo &&
          docType == other.docType &&
          holdingsSummary == other.holdingsSummary &&
          detailUrl == other.detailUrl;
}

class BookLocation {
  final String location;
  final String status;

  const BookLocation({required this.location, required this.status});

  @override
  int get hashCode => location.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookLocation &&
          runtimeType == other.runtimeType &&
          location == other.location &&
          status == other.status;
}

/// Advanced search parameters mirroring the OPAC search_more.php form.
class BookSearchParams {
  final String searchType;
  final String query;
  final String doctype;
  final String langCode;
  final int displaypg;
  final String sort;
  final String orderby;
  final String dept;
  final String showmode;
  final int page;

  const BookSearchParams({
    required this.searchType,
    required this.query,
    required this.doctype,
    required this.langCode,
    required this.displaypg,
    required this.sort,
    required this.orderby,
    required this.dept,
    required this.showmode,
    required this.page,
  });

  Future<String> buildUrl() => RustLib.instance.api
      .crateApiBookModelsBookSearchParamsBuildUrl(that: this);

  static Future<BookSearchParams> default_() =>
      RustLib.instance.api.crateApiBookModelsBookSearchParamsDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BookSearchParams> newInstance({required String query}) =>
      RustLib.instance.api.crateApiBookModelsBookSearchParamsNew(query: query);

  @override
  int get hashCode =>
      searchType.hashCode ^
      query.hashCode ^
      doctype.hashCode ^
      langCode.hashCode ^
      displaypg.hashCode ^
      sort.hashCode ^
      orderby.hashCode ^
      dept.hashCode ^
      showmode.hashCode ^
      page.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSearchParams &&
          runtimeType == other.runtimeType &&
          searchType == other.searchType &&
          query == other.query &&
          doctype == other.doctype &&
          langCode == other.langCode &&
          displaypg == other.displaypg &&
          sort == other.sort &&
          orderby == other.orderby &&
          dept == other.dept &&
          showmode == other.showmode &&
          page == other.page;
}

class BookSearchResult {
  final List<BookInfo> books;
  final int totalCount;

  const BookSearchResult({required this.books, required this.totalCount});

  @override
  int get hashCode => books.hashCode ^ totalCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSearchResult &&
          runtimeType == other.runtimeType &&
          books == other.books &&
          totalCount == other.totalCount;
}
