// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_total_count`, `resolve_detail_url`, `search_and_parse`

Future<BookSearchResult> searchBooks({required String title}) =>
    RustLib.instance.api.crateApiBookSearchSearchBooks(title: title);

Future<BookSearchResult> searchBooksAdvanced({
  required BookSearchParams params,
}) =>
    RustLib.instance.api.crateApiBookSearchSearchBooksAdvanced(params: params);

Future<BookDetail> fetchBookLocations({required String detailUrl}) => RustLib
    .instance
    .api
    .crateApiBookSearchFetchBookLocations(detailUrl: detailUrl);
