name: curriculum_table
description: "一款轻盈优雅的跨平台课表应用。"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.0-210.2.beta

dependencies:
  flutter:
    sdk: flutter

  rust_lib_curriculum_table:
    path: rust_builder
  flutter_rust_bridge: 2.12.0
  kalender: ^0.16.0
  syncfusion_flutter_calendar: ^33.1.47
  flutter_onnxruntime: ^1.6.4
  image: ^4.8.0
  dio: ^5.9.2
  html: ^0.15.6
  riverpod: ^3.2.1
  flutter_riverpod: ^3.0.3
  window_manager: ^0.5.1
  dynamic_color: ^1.8.1
  flex_color_scheme: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/devmil/flutter_launcher_icons.git

flutter:
  uses-material-design: true
  assets:
    - model/common.onnx
    - model/common.json
    - assets/icon/icon.png
