name: li_curriculum_table
description: "一款轻盈优雅的跨平台课表应用。"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  rust_lib_li_curriculum_table:
    path: rust_builder
  flutter_rust_bridge: 2.12.0
  intl: ^0.20.2
  riverpod: ^3.2.1
  flutter_riverpod: ^3.3.1
  window_manager: ^0.5.1
  dynamic_color: ^1.8.1
  flex_color_scheme: ^8.4.0
  web: ^1.1.1
  flutter_secure_storage: ^10.0.0
  calendar_view: ^2.0.0
  infinite_calendar_view: ^2.11.3
  auto_size_text: ^3.0.0
  pool: ^1.5.2
  riverpod_annotation: ^4.0.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons:
    git:
      url: https://github.com/devmil/flutter_launcher_icons.git
  flutter_native_splash: ^2.4.4
  msix: ^3.16.13
  riverpod_generator: ^4.0.3
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  build_runner: ^2.4.15
  fastforge: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/models/

msix_config:
  display_name: 🍐课表
  publisher_display_name: fan
  identity_name: company.suite.flutterapp
  msix_version: 1.0.0.0
  logo_path: assets/icon/icon.png
  capabilities: internetClient, location, microphone, webcam

flutter_native_splash:
  color: "#0A7C6D"
  image: assets/icon/icon.png
  android_12:
    color: "#0A7C6D"
    image: assets/icon/icon.png
  web: false
  fullscreen: true
