// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<ArcSessionManager> getAuthorizedSession({
  String? username,
  String? password,
}) => RustLib.instance.api.crateApiAuthGetAuthorizedSession(
  username: username,
  password: password,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < SessionManager >>>
abstract class ArcSessionManager implements RustOpaqueInterface {}
