// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_image_url`, `fetch_dangdang_cover`, `fetch_douban_cover`, `gb_extract_thumbnail`, `google_books_cover`, `ol_cover_by_isbn`, `ol_cover_by_title`, `ol_fetch_cover_id`, `parse_total_count`, `resolve_detail_url`, `search_and_parse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<BookSearchResult> searchBooks({required String title}) =>
    RustLib.instance.api.crateApiBookSearchBooks(title: title);

/// Advanced search with full parameters.
Future<BookSearchResult> searchBooksAdvanced({
  required BookSearchParams params,
}) => RustLib.instance.api.crateApiBookSearchBooksAdvanced(params: params);

Future<BookDetail> fetchBookLocations({required String detailUrl}) =>
    RustLib.instance.api.crateApiBookFetchBookLocations(detailUrl: detailUrl);

/// Try to find a cover URL by ISBN, falling back to title search.
/// Sources: Open Library → Dangdang → Douban → Google Books
Future<String?> fetchCoverUrl({required String isbn, required String title}) =>
    RustLib.instance.api.crateApiBookFetchCoverUrl(isbn: isbn, title: title);

class BookDetail {
  final String isbn;
  final String price;
  final String pages;
  final List<BookLocation> locations;

  const BookDetail({
    required this.isbn,
    required this.price,
    required this.pages,
    required this.locations,
  });

  @override
  int get hashCode =>
      isbn.hashCode ^ price.hashCode ^ pages.hashCode ^ locations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookDetail &&
          runtimeType == other.runtimeType &&
          isbn == other.isbn &&
          price == other.price &&
          pages == other.pages &&
          locations == other.locations;
}

class BookInfo {
  final String title;
  final String author;
  final String publisher;
  final String callNo;
  final String docType;
  final String holdingsSummary;
  final String detailUrl;

  const BookInfo({
    required this.title,
    required this.author,
    required this.publisher,
    required this.callNo,
    required this.docType,
    required this.holdingsSummary,
    required this.detailUrl,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      author.hashCode ^
      publisher.hashCode ^
      callNo.hashCode ^
      docType.hashCode ^
      holdingsSummary.hashCode ^
      detailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          publisher == other.publisher &&
          callNo == other.callNo &&
          docType == other.docType &&
          holdingsSummary == other.holdingsSummary &&
          detailUrl == other.detailUrl;
}

class BookLocation {
  final String location;
  final String status;

  const BookLocation({required this.location, required this.status});

  @override
  int get hashCode => location.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookLocation &&
          runtimeType == other.runtimeType &&
          location == other.location &&
          status == other.status;
}

/// Advanced search parameters mirroring the OPAC search_more.php form.
class BookSearchParams {
  /// Search field: "title", "author", "publisher", "isbn", "keyword", "callno", "series"
  final String searchType;

  /// The search query text
  final String query;

  /// Document type filter (default "ALL")
  final String doctype;

  /// Language code filter (default "ALL")
  final String langCode;

  /// Results per page: 20, 30, 50, 100 (default 20)
  final int displaypg;

  /// Sort field (default "CATA_DATE")
  final String sort;

  /// Sort order: "asc" or "desc" (default "DESC")
  final String orderby;

  /// Campus filter: "ALL", "00"=南京, "06"=江阴 (default "ALL")
  final String dept;

  /// Show mode: "list" or "table" (default "list")
  final String showmode;

  /// Page number (1-based, default 1)
  final int page;

  const BookSearchParams({
    required this.searchType,
    required this.query,
    required this.doctype,
    required this.langCode,
    required this.displaypg,
    required this.sort,
    required this.orderby,
    required this.dept,
    required this.showmode,
    required this.page,
  });

  /// Build the search URL from parameters.
  Future<String> buildUrl() =>
      RustLib.instance.api.crateApiBookBookSearchParamsBuildUrl(that: this);

  static Future<BookSearchParams> default_() =>
      RustLib.instance.api.crateApiBookBookSearchParamsDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BookSearchParams> newInstance({required String query}) =>
      RustLib.instance.api.crateApiBookBookSearchParamsNew(query: query);

  @override
  int get hashCode =>
      searchType.hashCode ^
      query.hashCode ^
      doctype.hashCode ^
      langCode.hashCode ^
      displaypg.hashCode ^
      sort.hashCode ^
      orderby.hashCode ^
      dept.hashCode ^
      showmode.hashCode ^
      page.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSearchParams &&
          runtimeType == other.runtimeType &&
          searchType == other.searchType &&
          query == other.query &&
          doctype == other.doctype &&
          langCode == other.langCode &&
          displaypg == other.displaypg &&
          sort == other.sort &&
          orderby == other.orderby &&
          dept == other.dept &&
          showmode == other.showmode &&
          page == other.page;
}

/// Result of a book search including total count for pagination.
class BookSearchResult {
  final List<BookInfo> books;
  final int totalCount;

  const BookSearchResult({required this.books, required this.totalCount});

  @override
  int get hashCode => books.hashCode ^ totalCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookSearchResult &&
          runtimeType == other.runtimeType &&
          books == other.books &&
          totalCount == other.totalCount;
}
