// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_image_url`, `fetch_dangdang_cover`, `fetch_douban_cover`, `gb_extract_thumbnail`, `google_books_cover`, `ol_cover_by_isbn`, `ol_cover_by_title`, `ol_fetch_cover_id`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<List<BookInfo>> searchBooks({required String title}) =>
    RustLib.instance.api.crateApiBookSearchBooks(title: title);

Future<BookDetail> fetchBookLocations({required String detailUrl}) =>
    RustLib.instance.api.crateApiBookFetchBookLocations(detailUrl: detailUrl);

/// Try to find a cover URL by ISBN, falling back to title search.
/// Sources: Open Library → Dangdang → Douban → Google Books
Future<String?> fetchCoverUrl({required String isbn, required String title}) =>
    RustLib.instance.api.crateApiBookFetchCoverUrl(isbn: isbn, title: title);

class BookDetail {
  final String isbn;
  final String price;
  final String pages;
  final List<BookLocation> locations;

  const BookDetail({
    required this.isbn,
    required this.price,
    required this.pages,
    required this.locations,
  });

  @override
  int get hashCode =>
      isbn.hashCode ^ price.hashCode ^ pages.hashCode ^ locations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookDetail &&
          runtimeType == other.runtimeType &&
          isbn == other.isbn &&
          price == other.price &&
          pages == other.pages &&
          locations == other.locations;
}

class BookInfo {
  final String title;
  final String author;
  final String publisher;
  final String callNo;
  final String docType;
  final String holdingsSummary;
  final String detailUrl;

  const BookInfo({
    required this.title,
    required this.author,
    required this.publisher,
    required this.callNo,
    required this.docType,
    required this.holdingsSummary,
    required this.detailUrl,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      author.hashCode ^
      publisher.hashCode ^
      callNo.hashCode ^
      docType.hashCode ^
      holdingsSummary.hashCode ^
      detailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          author == other.author &&
          publisher == other.publisher &&
          callNo == other.callNo &&
          docType == other.docType &&
          holdingsSummary == other.holdingsSummary &&
          detailUrl == other.detailUrl;
}

class BookLocation {
  final String location;
  final String status;

  const BookLocation({required this.location, required this.status});

  @override
  int get hashCode => location.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookLocation &&
          runtimeType == other.runtimeType &&
          location == other.location &&
          status == other.status;
}
