// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../crawler/model.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_ocr_engine`

void initOcrEngine({required List<int> modelBytes}) =>
    RustLib.instance.api.crateApiCrawlerInitOcrEngine(modelBytes: modelBytes);

Future<TimetableRecord> fetchTimetableData({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiCrawlerFetchTimetableData(
  username: username,
  password: password,
);
