// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../crawler/model.dart';
import '../frb_generated.dart';
import 'auth.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_authorized_session`

Future<ArcSessionManager> getSharedSessionManager() =>
    RustLib.instance.api.crateApiCrawlerGetSharedSessionManager();

Future<TimetableRecord> fetchTimetableData({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiCrawlerFetchTimetableData(
  username: username,
  password: password,
);

Future<TimetableRecord> fetchTimetableWithSession() =>
    RustLib.instance.api.crateApiCrawlerFetchTimetableWithSession();

Future<QrLoginStart> startQrLogin() =>
    RustLib.instance.api.crateApiCrawlerStartQrLogin();

Future<String> pollQrLogin() =>
    RustLib.instance.api.crateApiCrawlerPollQrLogin();

Future<void> cancelQrLogin() =>
    RustLib.instance.api.crateApiCrawlerCancelQrLogin();

/// Restore cookies from a JSON blob previously produced by
/// [`persist_cookies_bytes`]. Used at startup to rehydrate the jar
/// from `flutter_secure_storage`. Must be called *before* the first
/// `get_shared_session_manager()` call so the SessionManager picks up
/// the preload on construction.
Future<BigInt> setInitialCookiesJson({required String json}) =>
    RustLib.instance.api.crateApiCrawlerSetInitialCookiesJson(json: json);

/// Snapshot the current cookie jar as JSON bytes. Returned to Dart
/// so it can persist the jar through `flutter_secure_storage`. The
/// `Vec` may be empty if the jar is empty.
Future<Uint8List> persistCookiesBytes() =>
    RustLib.instance.api.crateApiCrawlerPersistCookiesBytes();

/// Explicitly flush the in-memory cookie jar to disk. Returns the
/// number of cookies persisted. Called automatically after QR /
/// password login; this is mainly for the logout flow to wipe the
/// on-disk copy.
Future<BigInt> persistCookies() =>
    RustLib.instance.api.crateApiCrawlerPersistCookies();

/// Clear all persisted cookies both in-memory and on disk. The next
/// request after this will trigger a fresh login.
Future<void> clearPersistedCookies() =>
    RustLib.instance.api.crateApiCrawlerClearPersistedCookies();

/// Whether any cookies for the CAS host are currently loaded. Cheap
/// probe used by Dart at startup to decide whether to show the login
/// dialog vs. attempt silent re-login.
Future<bool> hasCasCookies() =>
    RustLib.instance.api.crateApiCrawlerHasCasCookies();

/// Inject cookies from an external browser (WebView) login session into the
/// Rust HTTP client's cookie jar. Each cookie entry is a pair of
/// `(origin_url, cookie_string)` where:
/// - `origin_url` is like `https://bkjw.njust.edu.cn/njlgdx/framework/main.jsp`
/// - `cookie_string` is like `JSESSIONID=ABC123; Path=/njlgdx`
///
/// After injecting, this function verifies the session is valid by checking
/// the academic homepage. Returns Ok(()) on success, Err on failure.
Future<void> injectSessionCookies({required List<CookieEntry> cookies}) =>
    RustLib.instance.api.crateApiCrawlerInjectSessionCookies(cookies: cookies);

/// Check whether the current session is still valid (has authenticated cookies).
Future<bool> checkSessionValid() =>
    RustLib.instance.api.crateApiCrawlerCheckSessionValid();

Future<void> updateProxyConfig({required int port}) =>
    RustLib.instance.api.crateApiCrawlerUpdateProxyConfig(port: port);

Future<void> runProxyServer({required int port}) =>
    RustLib.instance.api.crateApiCrawlerRunProxyServer(port: port);

/// A cookie entry for FFI transport between Flutter and Rust.
class CookieEntry {
  final String url;
  final String cookie;

  const CookieEntry({required this.url, required this.cookie});

  @override
  int get hashCode => url.hashCode ^ cookie.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CookieEntry &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          cookie == other.cookie;
}

class QrLoginStart {
  final Uint8List imagePng;
  final bool alreadyAuthenticated;

  const QrLoginStart({
    required this.imagePng,
    required this.alreadyAuthenticated,
  });

  @override
  int get hashCode => imagePng.hashCode ^ alreadyAuthenticated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrLoginStart &&
          runtimeType == other.runtimeType &&
          imagePng == other.imagePng &&
          alreadyAuthenticated == other.alreadyAuthenticated;
}
