// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../crawler/model.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initOcrEngine({required List<int> modelBytes}) =>
    RustLib.instance.api.crateApiCrawlerInitOcrEngine(modelBytes: modelBytes);

Future<TimetableRecord> fetchTimetableData(
        {required String username, required String password}) =>
    RustLib.instance.api.crateApiCrawlerFetchTimetableData(
        username: username, password: password);

Future<ArcSessionManager> getSharedSessionManager() =>
    RustLib.instance.api.crateApiCrawlerGetSharedSessionManager();

Future<void> updateProxyConfig({required int port}) =>
    RustLib.instance.api.crateApiCrawlerUpdateProxyConfig(port: port);

Future<void> runProxyServer({required int port}) =>
    RustLib.instance.api.crateApiCrawlerRunProxyServer(port: port);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < SessionManager >>>
abstract class ArcSessionManager implements RustOpaqueInterface {}
