// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Build a [`reqwest::Client`] with browser-like headers, keep-alive, and a
/// generous timeout for the slow campus OPAC server.
Future<Client> buildClient() => RustLib.instance.api.crateApiHttpBuildClient();

Future<ClientBuilder> clientBuilder() =>
    RustLib.instance.api.crateApiHttpClientBuilder();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Client>>
abstract class Client implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< ClientBuilder>>
abstract class ClientBuilder implements RustOpaqueInterface {}
