// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Build a [`reqwest::Client`] with a 15 s timeout (native) or default (WASM).
/// The client is built once and reused across calls.
Future<Client> buildClient() => RustLib.instance.api.crateApiHttpBuildClient();

/// Return a [`reqwest::ClientBuilder`].
/// - Native: 15 s timeout, TLS via reqwest's `rustls` feature
/// - WASM: no timeout (browser handles it), no TLS config
Future<ClientBuilder> clientBuilder() =>
    RustLib.instance.api.crateApiHttpClientBuilder();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Client>>
abstract class Client implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< ClientBuilder>>
abstract class ClientBuilder implements RustOpaqueInterface {}
