// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_ctc`, `preprocess`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `classification`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DdddOcr>>
abstract class DdddOcr implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DdddOcr> newInstance({required List<int> modelBytes}) =>
      RustLib.instance.api.crateApiOcrDdddOcrNew(modelBytes: modelBytes);
}
