// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `install_rust_log_bridge`, `logger`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartLogBridge`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `enabled`, `flush`, `log`

/// Attaches a Dart-side stream to the Rust `log` crate.
///
/// This function intentionally owns a `StreamSink<RustLogEntry>` argument,
/// which makes flutter_rust_bridge expose it as a `Stream<RustLogEntry>` in
/// Dart. Records logged after this call are both printed to the console and
/// sent to Dart, where `AppLogger` persists them alongside Flutter logs.
Stream<RustLogEntry> initRustLogStream() =>
    RustLib.instance.api.crateApiRustLoggerInitRustLogStream();

/// A single Rust log record forwarded to Dart.
class RustLogEntry {
  final String level;
  final String module;
  final String message;

  const RustLogEntry({
    required this.level,
    required this.module,
    required this.message,
  });

  @override
  int get hashCode => level.hashCode ^ module.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLogEntry &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          module == other.module &&
          message == other.message;
}
