// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GitHubRelease`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<UpdateData> checkForUpdate() =>
    RustLib.instance.api.crateApiUpdateCheckForUpdate();

/// Stub for desktop/web platforms — download is not supported in-app.
Stream<DownloadProgress> downloadUpdate({
  required String url,
  required String savePath,
}) => RustLib.instance.api.crateApiUpdateDownloadUpdate(
  url: url,
  savePath: savePath,
);

class DownloadProgress {
  final BigInt received;
  final BigInt total;
  final bool done;
  final String savedPath;
  final String error;

  const DownloadProgress({
    required this.received,
    required this.total,
    required this.done,
    required this.savedPath,
    required this.error,
  });

  @override
  int get hashCode =>
      received.hashCode ^
      total.hashCode ^
      done.hashCode ^
      savedPath.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgress &&
          runtimeType == other.runtimeType &&
          received == other.received &&
          total == other.total &&
          done == other.done &&
          savedPath == other.savedPath &&
          error == other.error;
}

class UpdateData {
  final String latestVersion;
  final String releaseUrl;
  final String releaseNotes;
  final String publishedAt;

  const UpdateData({
    required this.latestVersion,
    required this.releaseUrl,
    required this.releaseNotes,
    required this.publishedAt,
  });

  @override
  int get hashCode =>
      latestVersion.hashCode ^
      releaseUrl.hashCode ^
      releaseNotes.hashCode ^
      publishedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateData &&
          runtimeType == other.runtimeType &&
          latestVersion == other.latestVersion &&
          releaseUrl == other.releaseUrl &&
          releaseNotes == other.releaseNotes &&
          publishedAt == other.publishedAt;
}
