// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CurrentWeather`, `OpenMeteoResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<WeatherData> fetchWeather({
  required double latitude,
  required double longitude,
}) => RustLib.instance.api.crateApiWeatherFetchWeather(
  latitude: latitude,
  longitude: longitude,
);

class WeatherData {
  final double temperature;
  final int weatherCode;
  final bool isDay;
  final double? windSpeed;

  const WeatherData({
    required this.temperature,
    required this.weatherCode,
    required this.isDay,
    this.windSpeed,
  });

  @override
  int get hashCode =>
      temperature.hashCode ^
      weatherCode.hashCode ^
      isDay.hashCode ^
      windSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeatherData &&
          runtimeType == other.runtimeType &&
          temperature == other.temperature &&
          weatherCode == other.weatherCode &&
          isDay == other.isDay &&
          windSpeed == other.windSpeed;
}
