display_name: 🍐课表

icon: assets/icon/icon.png

keywords:
  - 课表
  - timetable
  - 教务
  - 成绩
  - 空闲教室

generic_name: Curriculum Timetable

metainfo: linux/packaging/li_curriculum_table.appdata.xml

categories:
  - Education
  - Utility

startup_notify: true

include: []
