[package]
name = "rust_lib_li_curriculum_table"
version = "0.1.0"
edition = "2021"

[features]
default = []

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    "-O3",
    "--enable-bulk-memory",
    "--enable-threads",
    "--enable-mutable-globals",
    "--enable-nontrapping-float-to-int",
    "--enable-simd",
]

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.13.0"
reqwest = { version = "0.13.5", default-features = false, features = [
    "cookies",
    "json",
    "stream",
    "rustls",
] }
log = "0.4.34"
scraper = "0.27.0"
thiserror = "2.0.21"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
anyhow = "1.0.104"
tokio = { version = "1.53.1", features = ["sync", "macros"] }
futures-util = "0.3.34"
regex-lite = "0.1.9"
url = "2.5.8"
encoding_rs = "0.8.42"
rayon = "1.12.0"
aes = "0.9.3"
base64 = "0.23.1"
getrandom = { version = "0.4.3", features = ["wasm_js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.53.1", features = ["net", "time", "fs", "io-util"] }
mimalloc = "0.1.52"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.22.4"
rustls-platform-verifier = "0.7.1"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
strip = true
debug = false
debug-assertions = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
