// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/book/cover.dart';
import 'api/book/models.dart';
import 'api/book/search.dart';
import 'api/classroom.dart';
import 'api/crawler.dart';
import 'api/exam.dart';
import 'api/grade.dart';
import 'api/http.dart';
import 'api/level_exam_score.dart';
import 'api/update.dart';
import 'api/weather.dart';
import 'crawler/model.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1663616427;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_li_curriculum_table',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiBookModelsBookSearchParamsBuildUrl({
    required BookSearchParams that,
  });

  Future<BookSearchParams> crateApiBookModelsBookSearchParamsDefault();

  Future<BookSearchParams> crateApiBookModelsBookSearchParamsNew({
    required String query,
  });

  Future<Client> crateApiHttpBuildClient();

  Future<UpdateData> crateApiUpdateCheckForUpdate();

  Future<ClientBuilder> crateApiHttpClientBuilder();

  Stream<DownloadProgress> crateApiUpdateDownloadUpdate({
    required String url,
    required String savePath,
    required List<String> mirrorPrefixes,
  });

  Future<BookDetail> crateApiBookSearchFetchBookLocations({
    required String detailUrl,
  });

  Future<String?> crateApiBookCoverFetchCoverUrl({
    required String isbn,
    required String title,
  });

  Future<TimetableRecord> crateApiCrawlerFetchTimetableData({
    required String username,
    required String password,
  });

  Future<WeatherData> crateApiWeatherFetchWeather({
    required double latitude,
    required double longitude,
  });

  Future<ArcSessionManager> crateApiAuthGetAuthorizedSession({
    String? username,
    String? password,
  });

  Future<List<ClassroomSchedule>> crateApiClassroomGetBuildingSchedule({
    required String campusId,
    required String buildingId,
    required String term,
    String? username,
    String? password,
  });

  Future<List<Building>> crateApiClassroomGetBuildings({
    required String campusId,
    String? username,
    String? password,
  });

  Future<CampusPageData> crateApiClassroomGetCampuses({
    String? username,
    String? password,
  });

  Future<List<ClassroomAvailability>>
  crateApiClassroomGetClassroomAvailability({
    required String campusId,
    required String buildingId,
    required int week,
    required int weekday,
    required String term,
    String? username,
    String? password,
  });

  Future<List<Exam>> crateApiExamGetExams({
    required String username,
    required String password,
  });

  Future<List<Grade>> crateApiGradeGetGrades({
    required String username,
    required String password,
  });

  Future<List<LevelExamScore>> crateApiLevelExamScoreGetLevelExamScores({
    required String username,
    required String password,
  });

  Future<ArcSessionManager> crateApiCrawlerGetSharedSessionManager();

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiCrawlerInitOcrEngine();

  Future<void> crateApiCrawlerRunProxyServer({required int port});

  Future<BookSearchResult> crateApiBookSearchSearchBooks({
    required String title,
  });

  Future<BookSearchResult> crateApiBookSearchSearchBooksAdvanced({
    required BookSearchParams params,
  });

  Future<void> crateApiCrawlerUpdateProxyConfig({required int port});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcSessionManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcSessionManager;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcSessionManagerPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Client;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Client;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ClientPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClientBuilder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClientBuilder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClientBuilderPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiBookModelsBookSearchParamsBuildUrl({
    required BookSearchParams that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_book_search_params(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBookModelsBookSearchParamsBuildUrlConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookModelsBookSearchParamsBuildUrlConstMeta =>
      const TaskConstMeta(
        debugName: "book_search_params_build_url",
        argNames: ["that"],
      );

  @override
  Future<BookSearchParams> crateApiBookModelsBookSearchParamsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_search_params,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBookModelsBookSearchParamsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookModelsBookSearchParamsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "book_search_params_default",
        argNames: [],
      );

  @override
  Future<BookSearchParams> crateApiBookModelsBookSearchParamsNew({
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_search_params,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBookModelsBookSearchParamsNewConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookModelsBookSearchParamsNewConstMeta =>
      const TaskConstMeta(
        debugName: "book_search_params_new",
        argNames: ["query"],
      );

  @override
  Future<Client> crateApiHttpBuildClient() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHttpBuildClientConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpBuildClientConstMeta =>
      const TaskConstMeta(debugName: "build_client", argNames: []);

  @override
  Future<UpdateData> crateApiUpdateCheckForUpdate() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_update_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateCheckForUpdateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateCheckForUpdateConstMeta =>
      const TaskConstMeta(debugName: "check_for_update", argNames: []);

  @override
  Future<ClientBuilder> crateApiHttpClientBuilder() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHttpClientBuilderConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHttpClientBuilderConstMeta =>
      const TaskConstMeta(debugName: "client_builder", argNames: []);

  @override
  Stream<DownloadProgress> crateApiUpdateDownloadUpdate({
    required String url,
    required String savePath,
    required List<String> mirrorPrefixes,
  }) {
    final sink = RustStreamSink<DownloadProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(url, serializer);
            sse_encode_String(savePath, serializer);
            sse_encode_list_String(mirrorPrefixes, serializer);
            sse_encode_StreamSink_download_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiUpdateDownloadUpdateConstMeta,
          argValues: [url, savePath, mirrorPrefixes, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiUpdateDownloadUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "download_update",
        argNames: ["url", "savePath", "mirrorPrefixes", "sink"],
      );

  @override
  Future<BookDetail> crateApiBookSearchFetchBookLocations({
    required String detailUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(detailUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_detail,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookSearchFetchBookLocationsConstMeta,
        argValues: [detailUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookSearchFetchBookLocationsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_book_locations",
        argNames: ["detailUrl"],
      );

  @override
  Future<String?> crateApiBookCoverFetchCoverUrl({
    required String isbn,
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(isbn, serializer);
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookCoverFetchCoverUrlConstMeta,
        argValues: [isbn, title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookCoverFetchCoverUrlConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_cover_url",
        argNames: ["isbn", "title"],
      );

  @override
  Future<TimetableRecord> crateApiCrawlerFetchTimetableData({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_timetable_record,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFetchTimetableDataConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFetchTimetableDataConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_timetable_data",
        argNames: ["username", "password"],
      );

  @override
  Future<WeatherData> crateApiWeatherFetchWeather({
    required double latitude,
    required double longitude,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(latitude, serializer);
          sse_encode_f_64(longitude, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_weather_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWeatherFetchWeatherConstMeta,
        argValues: [latitude, longitude],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWeatherFetchWeatherConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_weather",
        argNames: ["latitude", "longitude"],
      );

  @override
  Future<ArcSessionManager> crateApiAuthGetAuthorizedSession({
    String? username,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAuthGetAuthorizedSessionConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthGetAuthorizedSessionConstMeta =>
      const TaskConstMeta(
        debugName: "get_authorized_session",
        argNames: ["username", "password"],
      );

  @override
  Future<List<ClassroomSchedule>> crateApiClassroomGetBuildingSchedule({
    required String campusId,
    required String buildingId,
    required String term,
    String? username,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(campusId, serializer);
          sse_encode_String(buildingId, serializer);
          sse_encode_String(term, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_classroom_schedule,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClassroomGetBuildingScheduleConstMeta,
        argValues: [campusId, buildingId, term, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClassroomGetBuildingScheduleConstMeta =>
      const TaskConstMeta(
        debugName: "get_building_schedule",
        argNames: ["campusId", "buildingId", "term", "username", "password"],
      );

  @override
  Future<List<Building>> crateApiClassroomGetBuildings({
    required String campusId,
    String? username,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(campusId, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_building,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClassroomGetBuildingsConstMeta,
        argValues: [campusId, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClassroomGetBuildingsConstMeta =>
      const TaskConstMeta(
        debugName: "get_buildings",
        argNames: ["campusId", "username", "password"],
      );

  @override
  Future<CampusPageData> crateApiClassroomGetCampuses({
    String? username,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_campus_page_data,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClassroomGetCampusesConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClassroomGetCampusesConstMeta =>
      const TaskConstMeta(
        debugName: "get_campuses",
        argNames: ["username", "password"],
      );

  @override
  Future<List<ClassroomAvailability>>
  crateApiClassroomGetClassroomAvailability({
    required String campusId,
    required String buildingId,
    required int week,
    required int weekday,
    required String term,
    String? username,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(campusId, serializer);
          sse_encode_String(buildingId, serializer);
          sse_encode_u_32(week, serializer);
          sse_encode_u_32(weekday, serializer);
          sse_encode_String(term, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_classroom_availability,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiClassroomGetClassroomAvailabilityConstMeta,
        argValues: [
          campusId,
          buildingId,
          week,
          weekday,
          term,
          username,
          password,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClassroomGetClassroomAvailabilityConstMeta =>
      const TaskConstMeta(
        debugName: "get_classroom_availability",
        argNames: [
          "campusId",
          "buildingId",
          "week",
          "weekday",
          "term",
          "username",
          "password",
        ],
      );

  @override
  Future<List<Exam>> crateApiExamGetExams({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_exam,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExamGetExamsConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExamGetExamsConstMeta => const TaskConstMeta(
    debugName: "get_exams",
    argNames: ["username", "password"],
  );

  @override
  Future<List<Grade>> crateApiGradeGetGrades({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_grade,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGradeGetGradesConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGradeGetGradesConstMeta => const TaskConstMeta(
    debugName: "get_grades",
    argNames: ["username", "password"],
  );

  @override
  Future<List<LevelExamScore>> crateApiLevelExamScoreGetLevelExamScores({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_level_exam_score,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLevelExamScoreGetLevelExamScoresConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLevelExamScoreGetLevelExamScoresConstMeta =>
      const TaskConstMeta(
        debugName: "get_level_exam_scores",
        argNames: ["username", "password"],
      );

  @override
  Future<ArcSessionManager> crateApiCrawlerGetSharedSessionManager() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerGetSharedSessionManagerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerGetSharedSessionManagerConstMeta =>
      const TaskConstMeta(
        debugName: "get_shared_session_manager",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiCrawlerInitOcrEngine() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerInitOcrEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerInitOcrEngineConstMeta =>
      const TaskConstMeta(debugName: "init_ocr_engine", argNames: []);

  @override
  Future<void> crateApiCrawlerRunProxyServer({required int port}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCrawlerRunProxyServerConstMeta,
        argValues: [port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerRunProxyServerConstMeta =>
      const TaskConstMeta(debugName: "run_proxy_server", argNames: ["port"]);

  @override
  Future<BookSearchResult> crateApiBookSearchSearchBooks({
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookSearchSearchBooksConstMeta,
        argValues: [title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookSearchSearchBooksConstMeta =>
      const TaskConstMeta(debugName: "search_books", argNames: ["title"]);

  @override
  Future<BookSearchResult> crateApiBookSearchSearchBooksAdvanced({
    required BookSearchParams params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_book_search_params(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_book_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBookSearchSearchBooksAdvancedConstMeta,
        argValues: [params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBookSearchSearchBooksAdvancedConstMeta =>
      const TaskConstMeta(
        debugName: "search_books_advanced",
        argNames: ["params"],
      );

  @override
  Future<void> crateApiCrawlerUpdateProxyConfig({required int port}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCrawlerUpdateProxyConfigConstMeta,
        argValues: [port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerUpdateProxyConfigConstMeta =>
      const TaskConstMeta(debugName: "update_proxy_config", argNames: ["port"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ArcSessionManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ArcSessionManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Client => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Client => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ClientBuilder => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ClientBuilder => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ArcSessionManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcSessionManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Client
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClientBuilder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientBuilderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ArcSessionManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ArcSessionManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Client
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ClientBuilder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ClientBuilderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<DownloadProgress> dco_decode_StreamSink_download_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BookDetail dco_decode_book_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BookDetail(
      isbn: dco_decode_String(arr[0]),
      price: dco_decode_String(arr[1]),
      pages: dco_decode_String(arr[2]),
      locations: dco_decode_list_book_location(arr[3]),
    );
  }

  @protected
  BookInfo dco_decode_book_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BookInfo(
      title: dco_decode_String(arr[0]),
      author: dco_decode_String(arr[1]),
      publisher: dco_decode_String(arr[2]),
      callNo: dco_decode_String(arr[3]),
      docType: dco_decode_String(arr[4]),
      holdingsSummary: dco_decode_String(arr[5]),
      detailUrl: dco_decode_String(arr[6]),
    );
  }

  @protected
  BookLocation dco_decode_book_location(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BookLocation(
      location: dco_decode_String(arr[0]),
      status: dco_decode_String(arr[1]),
    );
  }

  @protected
  BookSearchParams dco_decode_book_search_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return BookSearchParams(
      searchType: dco_decode_String(arr[0]),
      query: dco_decode_String(arr[1]),
      doctype: dco_decode_String(arr[2]),
      langCode: dco_decode_String(arr[3]),
      displaypg: dco_decode_u_32(arr[4]),
      sort: dco_decode_String(arr[5]),
      orderby: dco_decode_String(arr[6]),
      dept: dco_decode_String(arr[7]),
      showmode: dco_decode_String(arr[8]),
      page: dco_decode_u_32(arr[9]),
    );
  }

  @protected
  BookSearchResult dco_decode_book_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BookSearchResult(
      books: dco_decode_list_book_info(arr[0]),
      totalCount: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BookSearchParams dco_decode_box_autoadd_book_search_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_book_search_params(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Building dco_decode_building(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Building(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  Campus dco_decode_campus(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Campus(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  CampusPageData dco_decode_campus_page_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CampusPageData(
      campuses: dco_decode_list_campus(arr[0]),
      currentTerm: dco_decode_String(arr[1]),
    );
  }

  @protected
  ClassroomAvailability dco_decode_classroom_availability(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ClassroomAvailability(
      classroomName: dco_decode_String(arr[0]),
      availability: dco_decode_list_bool(arr[1]),
    );
  }

  @protected
  ClassroomSchedule dco_decode_classroom_schedule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ClassroomSchedule(
      classroomName: dco_decode_String(arr[0]),
      occupiedSlots: dco_decode_list_occupied_slot(arr[1]),
    );
  }

  @protected
  CourseRow dco_decode_course_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return CourseRow(
      courseId: dco_decode_String(arr[0]),
      order: dco_decode_String(arr[1]),
      courseName: dco_decode_String(arr[2]),
      teacher: dco_decode_String(arr[3]),
      timeText: dco_decode_String(arr[4]),
      credit: dco_decode_String(arr[5]),
      location: dco_decode_String(arr[6]),
      courseType: dco_decode_String(arr[7]),
      stage: dco_decode_String(arr[8]),
      slots: dco_decode_list_time_slot(arr[9]),
    );
  }

  @protected
  DownloadProgress dco_decode_download_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DownloadProgress(
      received: dco_decode_u_64(arr[0]),
      total: dco_decode_u_64(arr[1]),
      done: dco_decode_bool(arr[2]),
      savedPath: dco_decode_String(arr[3]),
      error: dco_decode_String(arr[4]),
    );
  }

  @protected
  Exam dco_decode_exam(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Exam(
      session: dco_decode_String(arr[0]),
      courseCode: dco_decode_String(arr[1]),
      courseName: dco_decode_String(arr[2]),
      examTime: dco_decode_String(arr[3]),
      location: dco_decode_String(arr[4]),
      seatNumber: dco_decode_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Grade dco_decode_grade(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Grade(
      term: dco_decode_String(arr[0]),
      courseCode: dco_decode_String(arr[1]),
      courseName: dco_decode_String(arr[2]),
      score: dco_decode_String(arr[3]),
      scoreMark: dco_decode_String(arr[4]),
      credits: dco_decode_f_64(arr[5]),
      totalHours: dco_decode_u_32(arr[6]),
      assessmentMethod: dco_decode_String(arr[7]),
      courseAttribute: dco_decode_String(arr[8]),
      courseNature: dco_decode_String(arr[9]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LevelExamScore dco_decode_level_exam_score(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return LevelExamScore(
      courseName: dco_decode_String(arr[0]),
      writtenScore: dco_decode_String(arr[1]),
      practicalScore: dco_decode_String(arr[2]),
      totalScore: dco_decode_String(arr[3]),
      writtenGrade: dco_decode_String(arr[4]),
      practicalGrade: dco_decode_String(arr[5]),
      totalGrade: dco_decode_String(arr[6]),
      examDate: dco_decode_String(arr[7]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BookInfo> dco_decode_list_book_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book_info).toList();
  }

  @protected
  List<BookLocation> dco_decode_list_book_location(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_book_location).toList();
  }

  @protected
  List<bool> dco_decode_list_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bool).toList();
  }

  @protected
  List<Building> dco_decode_list_building(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_building).toList();
  }

  @protected
  List<Campus> dco_decode_list_campus(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_campus).toList();
  }

  @protected
  List<ClassroomAvailability> dco_decode_list_classroom_availability(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_classroom_availability)
        .toList();
  }

  @protected
  List<ClassroomSchedule> dco_decode_list_classroom_schedule(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_classroom_schedule).toList();
  }

  @protected
  List<CourseRow> dco_decode_list_course_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_course_row).toList();
  }

  @protected
  List<Exam> dco_decode_list_exam(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_exam).toList();
  }

  @protected
  List<Grade> dco_decode_list_grade(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_grade).toList();
  }

  @protected
  List<LevelExamScore> dco_decode_list_level_exam_score(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_level_exam_score).toList();
  }

  @protected
  List<OccupiedSlot> dco_decode_list_occupied_slot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_occupied_slot).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TimeSlot> dco_decode_list_time_slot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_time_slot).toList();
  }

  @protected
  OccupiedSlot dco_decode_occupied_slot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return OccupiedSlot(
      startWeek: dco_decode_u_32(arr[0]),
      endWeek: dco_decode_u_32(arr[1]),
      weekday: dco_decode_u_32(arr[2]),
      slotIndex: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  TimeSlot dco_decode_time_slot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TimeSlot(
      weekday: dco_decode_u_32(arr[0]),
      startSection: dco_decode_u_32(arr[1]),
      endSection: dco_decode_u_32(arr[2]),
      startWeek: dco_decode_u_32(arr[3]),
      endWeek: dco_decode_u_32(arr[4]),
      weekText: dco_decode_String(arr[5]),
    );
  }

  @protected
  TimetableRecord dco_decode_timetable_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TimetableRecord(
      headers: dco_decode_list_String(arr[0]),
      rows: dco_decode_list_course_row(arr[1]),
      loginLikelySuccess: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateData dco_decode_update_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UpdateData(
      latestVersion: dco_decode_String(arr[0]),
      releaseUrl: dco_decode_String(arr[1]),
      releaseNotes: dco_decode_String(arr[2]),
      publishedAt: dco_decode_String(arr[3]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WeatherData dco_decode_weather_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WeatherData(
      minTemperature: dco_decode_f_64(arr[0]),
      maxTemperature: dco_decode_f_64(arr[1]),
      weatherCode: dco_decode_i_32(arr[2]),
      isDay: dco_decode_bool(arr[3]),
      windSpeed: dco_decode_opt_box_autoadd_f_64(arr[4]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ArcSessionManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcSessionManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Client
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClientBuilder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClientBuilderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ArcSessionManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ArcSessionManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Client
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClientImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ClientBuilder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ClientBuilderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<DownloadProgress> sse_decode_StreamSink_download_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BookDetail sse_decode_book_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isbn = sse_decode_String(deserializer);
    var var_price = sse_decode_String(deserializer);
    var var_pages = sse_decode_String(deserializer);
    var var_locations = sse_decode_list_book_location(deserializer);
    return BookDetail(
      isbn: var_isbn,
      price: var_price,
      pages: var_pages,
      locations: var_locations,
    );
  }

  @protected
  BookInfo sse_decode_book_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_publisher = sse_decode_String(deserializer);
    var var_callNo = sse_decode_String(deserializer);
    var var_docType = sse_decode_String(deserializer);
    var var_holdingsSummary = sse_decode_String(deserializer);
    var var_detailUrl = sse_decode_String(deserializer);
    return BookInfo(
      title: var_title,
      author: var_author,
      publisher: var_publisher,
      callNo: var_callNo,
      docType: var_docType,
      holdingsSummary: var_holdingsSummary,
      detailUrl: var_detailUrl,
    );
  }

  @protected
  BookLocation sse_decode_book_location(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_location = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return BookLocation(location: var_location, status: var_status);
  }

  @protected
  BookSearchParams sse_decode_book_search_params(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_searchType = sse_decode_String(deserializer);
    var var_query = sse_decode_String(deserializer);
    var var_doctype = sse_decode_String(deserializer);
    var var_langCode = sse_decode_String(deserializer);
    var var_displaypg = sse_decode_u_32(deserializer);
    var var_sort = sse_decode_String(deserializer);
    var var_orderby = sse_decode_String(deserializer);
    var var_dept = sse_decode_String(deserializer);
    var var_showmode = sse_decode_String(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    return BookSearchParams(
      searchType: var_searchType,
      query: var_query,
      doctype: var_doctype,
      langCode: var_langCode,
      displaypg: var_displaypg,
      sort: var_sort,
      orderby: var_orderby,
      dept: var_dept,
      showmode: var_showmode,
      page: var_page,
    );
  }

  @protected
  BookSearchResult sse_decode_book_search_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_books = sse_decode_list_book_info(deserializer);
    var var_totalCount = sse_decode_u_32(deserializer);
    return BookSearchResult(books: var_books, totalCount: var_totalCount);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BookSearchParams sse_decode_box_autoadd_book_search_params(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_book_search_params(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  Building sse_decode_building(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return Building(id: var_id, name: var_name);
  }

  @protected
  Campus sse_decode_campus(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return Campus(id: var_id, name: var_name);
  }

  @protected
  CampusPageData sse_decode_campus_page_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_campuses = sse_decode_list_campus(deserializer);
    var var_currentTerm = sse_decode_String(deserializer);
    return CampusPageData(campuses: var_campuses, currentTerm: var_currentTerm);
  }

  @protected
  ClassroomAvailability sse_decode_classroom_availability(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_classroomName = sse_decode_String(deserializer);
    var var_availability = sse_decode_list_bool(deserializer);
    return ClassroomAvailability(
      classroomName: var_classroomName,
      availability: var_availability,
    );
  }

  @protected
  ClassroomSchedule sse_decode_classroom_schedule(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_classroomName = sse_decode_String(deserializer);
    var var_occupiedSlots = sse_decode_list_occupied_slot(deserializer);
    return ClassroomSchedule(
      classroomName: var_classroomName,
      occupiedSlots: var_occupiedSlots,
    );
  }

  @protected
  CourseRow sse_decode_course_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_courseId = sse_decode_String(deserializer);
    var var_order = sse_decode_String(deserializer);
    var var_courseName = sse_decode_String(deserializer);
    var var_teacher = sse_decode_String(deserializer);
    var var_timeText = sse_decode_String(deserializer);
    var var_credit = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_courseType = sse_decode_String(deserializer);
    var var_stage = sse_decode_String(deserializer);
    var var_slots = sse_decode_list_time_slot(deserializer);
    return CourseRow(
      courseId: var_courseId,
      order: var_order,
      courseName: var_courseName,
      teacher: var_teacher,
      timeText: var_timeText,
      credit: var_credit,
      location: var_location,
      courseType: var_courseType,
      stage: var_stage,
      slots: var_slots,
    );
  }

  @protected
  DownloadProgress sse_decode_download_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_received = sse_decode_u_64(deserializer);
    var var_total = sse_decode_u_64(deserializer);
    var var_done = sse_decode_bool(deserializer);
    var var_savedPath = sse_decode_String(deserializer);
    var var_error = sse_decode_String(deserializer);
    return DownloadProgress(
      received: var_received,
      total: var_total,
      done: var_done,
      savedPath: var_savedPath,
      error: var_error,
    );
  }

  @protected
  Exam sse_decode_exam(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_session = sse_decode_String(deserializer);
    var var_courseCode = sse_decode_String(deserializer);
    var var_courseName = sse_decode_String(deserializer);
    var var_examTime = sse_decode_String(deserializer);
    var var_location = sse_decode_String(deserializer);
    var var_seatNumber = sse_decode_String(deserializer);
    return Exam(
      session: var_session,
      courseCode: var_courseCode,
      courseName: var_courseName,
      examTime: var_examTime,
      location: var_location,
      seatNumber: var_seatNumber,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Grade sse_decode_grade(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_term = sse_decode_String(deserializer);
    var var_courseCode = sse_decode_String(deserializer);
    var var_courseName = sse_decode_String(deserializer);
    var var_score = sse_decode_String(deserializer);
    var var_scoreMark = sse_decode_String(deserializer);
    var var_credits = sse_decode_f_64(deserializer);
    var var_totalHours = sse_decode_u_32(deserializer);
    var var_assessmentMethod = sse_decode_String(deserializer);
    var var_courseAttribute = sse_decode_String(deserializer);
    var var_courseNature = sse_decode_String(deserializer);
    return Grade(
      term: var_term,
      courseCode: var_courseCode,
      courseName: var_courseName,
      score: var_score,
      scoreMark: var_scoreMark,
      credits: var_credits,
      totalHours: var_totalHours,
      assessmentMethod: var_assessmentMethod,
      courseAttribute: var_courseAttribute,
      courseNature: var_courseNature,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LevelExamScore sse_decode_level_exam_score(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_courseName = sse_decode_String(deserializer);
    var var_writtenScore = sse_decode_String(deserializer);
    var var_practicalScore = sse_decode_String(deserializer);
    var var_totalScore = sse_decode_String(deserializer);
    var var_writtenGrade = sse_decode_String(deserializer);
    var var_practicalGrade = sse_decode_String(deserializer);
    var var_totalGrade = sse_decode_String(deserializer);
    var var_examDate = sse_decode_String(deserializer);
    return LevelExamScore(
      courseName: var_courseName,
      writtenScore: var_writtenScore,
      practicalScore: var_practicalScore,
      totalScore: var_totalScore,
      writtenGrade: var_writtenGrade,
      practicalGrade: var_practicalGrade,
      totalGrade: var_totalGrade,
      examDate: var_examDate,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookInfo> sse_decode_list_book_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookLocation> sse_decode_list_book_location(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookLocation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_book_location(deserializer));
    }
    return ans_;
  }

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <bool>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bool(deserializer));
    }
    return ans_;
  }

  @protected
  List<Building> sse_decode_list_building(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Building>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_building(deserializer));
    }
    return ans_;
  }

  @protected
  List<Campus> sse_decode_list_campus(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Campus>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_campus(deserializer));
    }
    return ans_;
  }

  @protected
  List<ClassroomAvailability> sse_decode_list_classroom_availability(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ClassroomAvailability>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_classroom_availability(deserializer));
    }
    return ans_;
  }

  @protected
  List<ClassroomSchedule> sse_decode_list_classroom_schedule(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ClassroomSchedule>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_classroom_schedule(deserializer));
    }
    return ans_;
  }

  @protected
  List<CourseRow> sse_decode_list_course_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CourseRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_course_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<Exam> sse_decode_list_exam(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Exam>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_exam(deserializer));
    }
    return ans_;
  }

  @protected
  List<Grade> sse_decode_list_grade(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Grade>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_grade(deserializer));
    }
    return ans_;
  }

  @protected
  List<LevelExamScore> sse_decode_list_level_exam_score(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LevelExamScore>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_level_exam_score(deserializer));
    }
    return ans_;
  }

  @protected
  List<OccupiedSlot> sse_decode_list_occupied_slot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OccupiedSlot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_occupied_slot(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TimeSlot> sse_decode_list_time_slot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TimeSlot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_time_slot(deserializer));
    }
    return ans_;
  }

  @protected
  OccupiedSlot sse_decode_occupied_slot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startWeek = sse_decode_u_32(deserializer);
    var var_endWeek = sse_decode_u_32(deserializer);
    var var_weekday = sse_decode_u_32(deserializer);
    var var_slotIndex = sse_decode_u_32(deserializer);
    return OccupiedSlot(
      startWeek: var_startWeek,
      endWeek: var_endWeek,
      weekday: var_weekday,
      slotIndex: var_slotIndex,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TimeSlot sse_decode_time_slot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_weekday = sse_decode_u_32(deserializer);
    var var_startSection = sse_decode_u_32(deserializer);
    var var_endSection = sse_decode_u_32(deserializer);
    var var_startWeek = sse_decode_u_32(deserializer);
    var var_endWeek = sse_decode_u_32(deserializer);
    var var_weekText = sse_decode_String(deserializer);
    return TimeSlot(
      weekday: var_weekday,
      startSection: var_startSection,
      endSection: var_endSection,
      startWeek: var_startWeek,
      endWeek: var_endWeek,
      weekText: var_weekText,
    );
  }

  @protected
  TimetableRecord sse_decode_timetable_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_headers = sse_decode_list_String(deserializer);
    var var_rows = sse_decode_list_course_row(deserializer);
    var var_loginLikelySuccess = sse_decode_bool(deserializer);
    return TimetableRecord(
      headers: var_headers,
      rows: var_rows,
      loginLikelySuccess: var_loginLikelySuccess,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateData sse_decode_update_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_latestVersion = sse_decode_String(deserializer);
    var var_releaseUrl = sse_decode_String(deserializer);
    var var_releaseNotes = sse_decode_String(deserializer);
    var var_publishedAt = sse_decode_String(deserializer);
    return UpdateData(
      latestVersion: var_latestVersion,
      releaseUrl: var_releaseUrl,
      releaseNotes: var_releaseNotes,
      publishedAt: var_publishedAt,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WeatherData sse_decode_weather_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_minTemperature = sse_decode_f_64(deserializer);
    var var_maxTemperature = sse_decode_f_64(deserializer);
    var var_weatherCode = sse_decode_i_32(deserializer);
    var var_isDay = sse_decode_bool(deserializer);
    var var_windSpeed = sse_decode_opt_box_autoadd_f_64(deserializer);
    return WeatherData(
      minTemperature: var_minTemperature,
      maxTemperature: var_maxTemperature,
      weatherCode: var_weatherCode,
      isDay: var_isDay,
      windSpeed: var_windSpeed,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager(
    ArcSessionManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcSessionManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    Client self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClientImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder(
    ClientBuilder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClientBuilderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcSessionManager(
    ArcSessionManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ArcSessionManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClient(
    Client self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClientImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClientBuilder(
    ClientBuilder self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ClientBuilderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_download_progress_Sse(
    RustStreamSink<DownloadProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_download_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_book_detail(BookDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.isbn, serializer);
    sse_encode_String(self.price, serializer);
    sse_encode_String(self.pages, serializer);
    sse_encode_list_book_location(self.locations, serializer);
  }

  @protected
  void sse_encode_book_info(BookInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.publisher, serializer);
    sse_encode_String(self.callNo, serializer);
    sse_encode_String(self.docType, serializer);
    sse_encode_String(self.holdingsSummary, serializer);
    sse_encode_String(self.detailUrl, serializer);
  }

  @protected
  void sse_encode_book_location(BookLocation self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.location, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_book_search_params(
    BookSearchParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.searchType, serializer);
    sse_encode_String(self.query, serializer);
    sse_encode_String(self.doctype, serializer);
    sse_encode_String(self.langCode, serializer);
    sse_encode_u_32(self.displaypg, serializer);
    sse_encode_String(self.sort, serializer);
    sse_encode_String(self.orderby, serializer);
    sse_encode_String(self.dept, serializer);
    sse_encode_String(self.showmode, serializer);
    sse_encode_u_32(self.page, serializer);
  }

  @protected
  void sse_encode_book_search_result(
    BookSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_book_info(self.books, serializer);
    sse_encode_u_32(self.totalCount, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_book_search_params(
    BookSearchParams self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_book_search_params(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_building(Building self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_campus(Campus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_campus_page_data(
    CampusPageData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_campus(self.campuses, serializer);
    sse_encode_String(self.currentTerm, serializer);
  }

  @protected
  void sse_encode_classroom_availability(
    ClassroomAvailability self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.classroomName, serializer);
    sse_encode_list_bool(self.availability, serializer);
  }

  @protected
  void sse_encode_classroom_schedule(
    ClassroomSchedule self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.classroomName, serializer);
    sse_encode_list_occupied_slot(self.occupiedSlots, serializer);
  }

  @protected
  void sse_encode_course_row(CourseRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.courseId, serializer);
    sse_encode_String(self.order, serializer);
    sse_encode_String(self.courseName, serializer);
    sse_encode_String(self.teacher, serializer);
    sse_encode_String(self.timeText, serializer);
    sse_encode_String(self.credit, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_String(self.courseType, serializer);
    sse_encode_String(self.stage, serializer);
    sse_encode_list_time_slot(self.slots, serializer);
  }

  @protected
  void sse_encode_download_progress(
    DownloadProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.received, serializer);
    sse_encode_u_64(self.total, serializer);
    sse_encode_bool(self.done, serializer);
    sse_encode_String(self.savedPath, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_exam(Exam self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.session, serializer);
    sse_encode_String(self.courseCode, serializer);
    sse_encode_String(self.courseName, serializer);
    sse_encode_String(self.examTime, serializer);
    sse_encode_String(self.location, serializer);
    sse_encode_String(self.seatNumber, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_grade(Grade self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.term, serializer);
    sse_encode_String(self.courseCode, serializer);
    sse_encode_String(self.courseName, serializer);
    sse_encode_String(self.score, serializer);
    sse_encode_String(self.scoreMark, serializer);
    sse_encode_f_64(self.credits, serializer);
    sse_encode_u_32(self.totalHours, serializer);
    sse_encode_String(self.assessmentMethod, serializer);
    sse_encode_String(self.courseAttribute, serializer);
    sse_encode_String(self.courseNature, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_level_exam_score(
    LevelExamScore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.courseName, serializer);
    sse_encode_String(self.writtenScore, serializer);
    sse_encode_String(self.practicalScore, serializer);
    sse_encode_String(self.totalScore, serializer);
    sse_encode_String(self.writtenGrade, serializer);
    sse_encode_String(self.practicalGrade, serializer);
    sse_encode_String(self.totalGrade, serializer);
    sse_encode_String(self.examDate, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book_info(
    List<BookInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_book_location(
    List<BookLocation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_book_location(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bool(item, serializer);
    }
  }

  @protected
  void sse_encode_list_building(List<Building> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_building(item, serializer);
    }
  }

  @protected
  void sse_encode_list_campus(List<Campus> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_campus(item, serializer);
    }
  }

  @protected
  void sse_encode_list_classroom_availability(
    List<ClassroomAvailability> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_classroom_availability(item, serializer);
    }
  }

  @protected
  void sse_encode_list_classroom_schedule(
    List<ClassroomSchedule> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_classroom_schedule(item, serializer);
    }
  }

  @protected
  void sse_encode_list_course_row(
    List<CourseRow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_course_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_exam(List<Exam> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_exam(item, serializer);
    }
  }

  @protected
  void sse_encode_list_grade(List<Grade> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_grade(item, serializer);
    }
  }

  @protected
  void sse_encode_list_level_exam_score(
    List<LevelExamScore> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_level_exam_score(item, serializer);
    }
  }

  @protected
  void sse_encode_list_occupied_slot(
    List<OccupiedSlot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_occupied_slot(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_time_slot(
    List<TimeSlot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_time_slot(item, serializer);
    }
  }

  @protected
  void sse_encode_occupied_slot(OccupiedSlot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.startWeek, serializer);
    sse_encode_u_32(self.endWeek, serializer);
    sse_encode_u_32(self.weekday, serializer);
    sse_encode_u_32(self.slotIndex, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_time_slot(TimeSlot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.weekday, serializer);
    sse_encode_u_32(self.startSection, serializer);
    sse_encode_u_32(self.endSection, serializer);
    sse_encode_u_32(self.startWeek, serializer);
    sse_encode_u_32(self.endWeek, serializer);
    sse_encode_String(self.weekText, serializer);
  }

  @protected
  void sse_encode_timetable_record(
    TimetableRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.headers, serializer);
    sse_encode_list_course_row(self.rows, serializer);
    sse_encode_bool(self.loginLikelySuccess, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_data(UpdateData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.latestVersion, serializer);
    sse_encode_String(self.releaseUrl, serializer);
    sse_encode_String(self.releaseNotes, serializer);
    sse_encode_String(self.publishedAt, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_weather_data(WeatherData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.minTemperature, serializer);
    sse_encode_f_64(self.maxTemperature, serializer);
    sse_encode_i_32(self.weatherCode, serializer);
    sse_encode_bool(self.isDay, serializer);
    sse_encode_opt_box_autoadd_f_64(self.windSpeed, serializer);
  }
}

@sealed
class ArcSessionManagerImpl extends RustOpaque implements ArcSessionManager {
  // Not to be used by end users
  ArcSessionManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ArcSessionManagerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ArcSessionManager,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ArcSessionManager,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_ArcSessionManagerPtr,
  );
}

@sealed
class ClientBuilderImpl extends RustOpaque implements ClientBuilder {
  // Not to be used by end users
  ClientBuilderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClientBuilderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ClientBuilder,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClientBuilder,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClientBuilderPtr,
  );
}

@sealed
class ClientImpl extends RustOpaque implements Client {
  // Not to be used by end users
  ClientImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ClientImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Client,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Client,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ClientPtr,
  );
}
