// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../update.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_download_client`, `race_connect`, `sequential_connect`, `stream_to_file`

Stream<DownloadProgress> doDownload({
  required String url,
  required String savePath,
  required List<String> mirrorPrefixes,
}) => RustLib.instance.api.crateApiUpdateDownloadDoDownload(
  url: url,
  savePath: savePath,
  mirrorPrefixes: mirrorPrefixes,
);
