// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CourseRow {
  final String courseId;
  final String order;
  final String courseName;
  final String teacher;
  final String timeText;
  final String credit;
  final String location;
  final String courseType;
  final String stage;
  final List<TimeSlot> slots;

  const CourseRow({
    required this.courseId,
    required this.order,
    required this.courseName,
    required this.teacher,
    required this.timeText,
    required this.credit,
    required this.location,
    required this.courseType,
    required this.stage,
    required this.slots,
  });

  @override
  int get hashCode =>
      courseId.hashCode ^
      order.hashCode ^
      courseName.hashCode ^
      teacher.hashCode ^
      timeText.hashCode ^
      credit.hashCode ^
      location.hashCode ^
      courseType.hashCode ^
      stage.hashCode ^
      slots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CourseRow &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId &&
          order == other.order &&
          courseName == other.courseName &&
          teacher == other.teacher &&
          timeText == other.timeText &&
          credit == other.credit &&
          location == other.location &&
          courseType == other.courseType &&
          stage == other.stage &&
          slots == other.slots;
}

class TimeSlot {
  final int weekday;
  final int startSection;
  final int endSection;
  final int startWeek;
  final int endWeek;
  final String weekText;

  const TimeSlot({
    required this.weekday,
    required this.startSection,
    required this.endSection,
    required this.startWeek,
    required this.endWeek,
    required this.weekText,
  });

  @override
  int get hashCode =>
      weekday.hashCode ^
      startSection.hashCode ^
      endSection.hashCode ^
      startWeek.hashCode ^
      endWeek.hashCode ^
      weekText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeSlot &&
          runtimeType == other.runtimeType &&
          weekday == other.weekday &&
          startSection == other.startSection &&
          endSection == other.endSection &&
          startWeek == other.startWeek &&
          endWeek == other.endWeek &&
          weekText == other.weekText;
}

class TimetableRecord {
  final List<String> headers;
  final List<CourseRow> rows;
  final bool loginLikelySuccess;

  const TimetableRecord({
    required this.headers,
    required this.rows,
    required this.loginLikelySuccess,
  });

  @override
  int get hashCode =>
      headers.hashCode ^ rows.hashCode ^ loginLikelySuccess.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimetableRecord &&
          runtimeType == other.runtimeType &&
          headers == other.headers &&
          rows == other.rows &&
          loginLikelySuccess == other.loginLikelySuccess;
}
